@startuml
' 
package "核心功能模块" {
  component 记账组件 [
    记账组件
  ]
  
  component 统计组件 [
    统计组件
  ]
  
  component 查找组件 [
    查找组件
  ]
  
  component 首页UI组件 [
    首页UI组件
  ]
}

package "支撑组件" {
  component 分类数据组件 [
    分类数据组件）
  ]
  
  component 交易数据组件 [
    交易数据组件
  ]
  
  component 数据校验组件 [
    数据校验组件
  ]
}

' 
分类数据组件 --> 记账组件 : 提供分类数据
记账组件 --> 数据校验组件 : 提交数据校验
数据校验组件 --> 交易数据组件 : 校验通过后存储

交易数据组件 --> 统计组件 : 提供统计数据源
交易数据组件 --> 查找组件 : 提供查询数据源
交易数据组件 --> 首页UI组件 : 提供近7天记录

首页UI组件 --> 记账组件 : 提供记账入口
首页UI组件 --> 统计组件 : 提供统计入口
查找组件 --> 首页UI组件 : 输出排序后列表
统计组件 --> 首页UI组件 : 输出图表展示数据
交易数据组件 --> 分类数据组件 : 提供分类数据
@enduml